<?php

const ROLE_ADMIN = 'Admin';

// for notif
const NOTIF_PETUNJUK_DAN_ARAHAN_SEND = 'PETUNJUK_DAN_ARAHAN_SEND';
const NOTIF_PETUNJUK_DAN_ARAHAN = 'PETUNJUK_DAN_ARAHAN';
const NOTIF_EVENT_PARTICIPANT = 'EVENT_PARTICIPANT';
